### ISSUE TITLE
Fails to install - 99.99% a user error

### ISSUE THREAD

**Issue by faanskit** [noelportugal/wyze-node#16]
Hi,

Complete node.js noob here, but need to start somewhere. Right.
Did try to google this, but finally gave up. Seeking some guidance to get this installed.

When running `npm install wyze-node --save` on a Windows 10 system I get the following error:
```
npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://artifactory.workday.com/artifactory/api/npm/npm-virtual/node-localstorage/-/node-localstorage-2.1.6.tgz
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

```

Sorry for bugging you with such simple questions.

Thanks, Marcus

**Comment by noelportugal** [comment]
Nah, asking questions is how we all learn! The first WARN should be ok, but just incase I just bumped the axios version to v.0.21.1.
The ERR might be on my side..Please try again and let me know!
```
npm install wyze-node --save
```

**Comment by noelportugal** [comment]
Also you might want to update your fork with my recent changes.

**Comment by faanskit** [comment]
> The ERR might be on my side..Please try again and let me know!

Worked now. Thanks! Please close the issue.

**Comment by faanskit** [comment]
Just need to say. Amazing and thanks!
This will save my day, and I need to enable this in Home Assistant.
Every time my lights turn on (by automation), I get a notification from Wyze.

I had planned to use IFTTT to do the following.
At sunset, (1) disable Wyze Cam, (2) turn on light and (3) enable Wyze Cam

But for IFTTT reasons I gave up. Now I'll try to convert this into a Home Assistant module.

Great work!
