### ISSUE TITLE
Does this stream video?

### ISSUE THREAD

**Issue by wesbos** [noelportugal/wyze-node#2]
Thanks for the lib - I'm a bit confused - are we able to stream video from our cameras with this?  Or is it just for getting a list of the devices?

**Comment by bverkron** [comment]
I would wager this will *not* stream video. Wyze cameras themselves need an alternate firmware to enable streaming officially. Also APIs are designed to send and receive data as JSON or other text formats not stream video, etc. It’s not clear from the doc but I would wager this would just allow programmatic control of camera features like toggling the camera or its options like night mode on / off.

**Comment by noelportugal** [comment]
Sorry it doesn't stream video...If you are looking for a way to access video your closest bet is using RTSP https://support.wyzecam.com/hc/en-us/articles/360026245231-Wyze-Cam-RTSP

**Comment by Nikolai-RR** [comment]
For anyone coming across this issue and thinking about using RTSP, it looks like they have removed the RTSP firmware in light of some CVEs that have surfaced with their firmware. No telling when it will become available again.

https://www.bitdefender.com/blog/labs/vulnerabilities-identified-in-wyze-cam-iot-device/
