### ISSUE TITLE
New error UnauthorizedOperation during login. 

### ISSUE THREAD

**Issue by HunterHeston** [noelportugal/wyze-node#21]
Hey I've been using this repo for a while without issue. Login was working as expected and I was able to turn devices on and off easily. 

However, login seems to be broken at the moment. Getting back this response when logging `result.data`  [here](https://github.com/noelportugal/wyze-node/blob/master/index.js#L88):

```txt
{ 
  ts: 1625055563361,
  code: '3005',
  msg: 'UnauthorizedOperation',
  data: {} 
}
```

I've verified my correct credentials so this may be due to a change the Wyze team made.

**Comment by noelportugal** [comment]
Hi, yes I had the same issue and fixed it a couple days ago. Please update the wyze-node package to ‘2.0.6’. The login endpoint changed.

**Comment by HunterHeston** [comment]
Awesome thanks I'll try that this evening.
