### ISSUE TITLE
Potential way to control wyze vacuum

### ISSUE THREAD

**Issue by TKDKid1000** [noelportugal/wyze-node#22]
Is it possible to implement wyze vacuum support? This way you could specify a device and then run clean, suction, and room query on a vacuum.

**Comment by wkrasner** [comment]
I have been using the app to get vacuum status, so I can put it on my dashboard.  Would love to be able to control vacuum.  

Thanks

Will

**Comment by jt-github** [comment]
It would be fantastic to control my vacuum this way.  It would absolutely blow my mind if you could get access to the live mapping data so that I could render my vacuum's progress on one of my monitors just because it would be ridiculous. :)
