### ISSUE TITLE
Device Id

### ISSUE THREAD

**Issue by micalexander** [noelportugal/wyze-node#3]
Hey, thanks for your work on this. Do you think you can give an example or point me to a decent article explaining how to get the device id using Wireshark? It sure would be greatly appreciated.

**Comment by dylankolson** [comment]
+1

**Comment by McMainsLiam** [comment]
For anyone still curious about this, these were the steps I took to find the phoneId using Charles proxy and my iPhone. They have a 30 day evaluation period so there's no upfront cost.

1. Install Charles proxy. It asked me for my password to autoconfigure the proxy, I hit allow and entered my password. Once the setup had been complete, I could start seeing my network traffic appearing from my computer.
2. Set up HTTP proxy on your iPhone. Following [this guide](https://www.charlesproxy.com/documentation/faqs/using-charles-from-an-iphone/) I was able to set up the proxy from my phone through Charles on my computer. Once this setup had been complete, I could see the requests that were being made on my phone appear on my computer as well.
3. Allow SSL proxying. Click on the Proxy button in the menu bar, click on SSL Proxying Settings, click Enable SSL Proxying, and then click "add" under the include section of SSL Proxying. Then enter `*` for host and `*` for port. This will allow all SSL connections to be proxied through Charles. It probably isn't the best setup in the long run but it got the job done for me.
4. Completely close out of the Wyze app on your phone. Clear the log on Charles and then begin a new recording session. Start up the Wyze app on your phone and you should see quite a few connections come through Charles. There should be a request to `https://wyze-platform-service.wyzecam.com` on the left hand side. Drill down into that request until you come across the `set_phone_status` endpoint. Open up the `Contents` tab on this endpoint and you should see something like this
```javascript
{
	"status": true,
	"phone_id": "f90d35e4-7c8a-4af5-93e3-767f5936a52d"
}
```
This is not my true phone_id so please don't try to use it. You should be set to go now. Hope this helps!

**Comment by noelportugal** [comment]
Hey @McMainsLiam your rock!! Thanks for adding this..I can add this to the README file. BTW I use the API EVERYDAY....for my custom garage door iOS app! https://forums.wyzecam.com/t/wyze-api-sense-camera-snapshot/107663
